### ISSUE TITLE
After unspecified number of rounds fails to record further saves

### ISSUE THREAD

**Issue by Mr-8k** [doombubbles/time-machine#3]
In this instance it was round 19, but I've seen it as early as round 11. Console prints this error after every round when it occurs:
```[14:39:15.957] During invoking native->managed trampoline
[14:39:15.957] [BloonsTD6_Mod_Helper] System.NullReferenceException: Object reference not set to an instance of an object.
   at Il2CppInterop.Runtime.InteropTypes.Il2CppObjectBase.CreateGCHandle(IntPtr objHdl) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/InteropTypes/Il2CppObjectBase.cs:line 49
   at Il2CppSystem.Nullable`1..ctor()
   at BTD_Mod_Helper.Api.Helpers.FileIOHelper.SaveObject(String fileName, Object data)
   at TimeMachine.InGame_RoundEnd.Postfix(InGame __instance, Int32 completedRound, Int32 highestCompletedRound) in /home/runner/work/time-machine/time-machine/TimeMachine/Patches.cs:line 32
   at DMD<Il2CppAssets.Scripts.Unity.UI_New.InGame.InGame::RoundEnd>(InGame this, Int32 completedRound, Int32 highestCompletedRound)
   at (il2cpp -> managed) RoundEnd(IntPtr , Int32 , Int32 , Il2CppMethodInfo* )```

**Comment by doombubbles** [comment]
Can you check if this build of Mod Helper fixes things for you? https://github.com/gurrenm3/BTD-Mod-Helper/actions/runs/6737231449

**Comment by oneparchy** [comment]
@doombubbles I had an issue consistent with what OP described and that updated Mod Helper build seemed to fix it.

**Comment by Mr-8k** [comment]
New build of mod helper appears to have fixed it, thanks.

**Comment by kmanb44** [comment]
@doombubbles I am also having this issue, and I have reinstalled the mod helper, and the time machine dll. any ideas?
