### ISSUE TITLE
missing methods 

### ISSUE THREAD

**Issue by eMGeeneer** [doombubbles/time-machine#8]
```
[15:19:32.692] [BloonsTD6_Mod_Helper] System.MissingMethodException: Method not found: 'Il2CppAssets.Scripts.Unity.Bridge.UnityToSimulation Il2CppAssets.Scripts.Unity.UI_New.InGame.InGame.get_UnityToSimulation()'.
   at TimeMachine.TimeMachineMod.CreateTimelineUI(GameObject mainPanel, Int32 yOffset)
   at TimeMachine.PauseScreen_Open.Postfix(PauseScreen __instance) in /home/runner/work/time-machine/time-machine/TimeMachine/Patches.cs:line 88
   at DMD<Il2CppAssets.Scripts.Unity.UI_New.Pause.PauseScreen::Open>(PauseScreen this, Object menuData)
   at (il2cpp -> managed) Open(IntPtr , IntPtr , Il2CppMethodInfo* )
[15:19:41.136] During invoking native->managed trampoline
[15:19:41.137] [BloonsTD6_Mod_Helper] System.MissingMethodException: Method not found: 'Il2CppAssets.Scripts.Unity.Bridge.UnityToSimulation Il2CppAssets.Scripts.Unity.UI_New.InGame.InGame.get_UnityToSimulation()'.
   at TimeMachine.TimeMachineMod.CreateTimelineUI(GameObject mainPanel, Int32 yOffset)
   at TimeMachine.PauseScreen_Open.Postfix(PauseScreen __instance) in /home/runner/work/time-machine/time-machine/TimeMachine/Patches.cs:line 88
   at DMD<Il2CppAssets.Scripts.Unity.UI_New.Pause.PauseScreen::Open>(PauseScreen this, Object menuData)
   at (il2cpp -> managed) Open(IntPtr , IntPtr , Il2CppMethodInfo* )
[15:19:43.202] During invoking native->managed trampoline
[15:19:43.202] [BloonsTD6_Mod_Helper] System.MissingMethodException: Method not found: 'Il2CppAssets.Scripts.Unity.Bridge.UnityToSimulation Il2CppAssets.Scripts.Unity.UI_New.InGame.InGame.get_UnityToSimulation()'.
   at TimeMachine.TimeMachineMod.CreateTimelineUI(GameObject mainPanel, Int32 yOffset)
   at TimeMachine.PauseScreen_Open.Postfix(PauseScreen __instance) in /home/runner/work/time-machine/time-machine/TimeMachine/Patches.cs:line 88
   at DMD<Il2CppAssets.Scripts.Unity.UI_New.Pause.PauseScreen::Open>(PauseScreen this, Object menuData)
   at (il2cpp -> managed) Open(IntPtr , IntPtr , Il2CppMethodInfo* )
[15:19:55.768] During invoking native->managed trampoline
[15:19:55.769] [BloonsTD6_Mod_Helper] System.MissingMethodException: Method not found: 'Il2CppAssets.Scripts.Unity.Bridge.UnityToSimulation Il2CppAssets.Scripts.Unity.UI_New.InGame.InGame.get_UnityToSimulation()'.
   at TimeMachine.TimeMachineMod.CreateTimelineUI(GameObject mainPanel, Int32 yOffset)
   at TimeMachine.PauseScreen_Open.Postfix(PauseScreen __instance) in /home/runner/work/time-machine/time-machine/TimeMachine/Patches.cs:line 88
   at DMD<Il2CppAssets.Scripts.Unity.UI_New.Pause.PauseScreen::Open>(PauseScreen this, Object menuData)
   at (il2cpp -> managed) Open(IntPtr , IntPtr , Il2CppMethodInfo* )
[15:24:10.180] During invoking native->managed trampoline
[15:24:10.180] [BloonsTD6_Mod_Helper] System.MissingMethodException: Method not found: 'Il2CppAssets.Scripts.Unity.Bridge.UnityToSimulation Il2CppAssets.Scripts.Unity.UI_New.InGame.InGame.get_UnityToSimulation()'.
   at TimeMachine.TimeMachineMod.CreateTimelineUI(GameObject mainPanel, Int32 yOffset)
   at TimeMachine.PauseScreen_Open.Postfix(PauseScreen __instance) in /home/runner/work/time-machine/time-machine/TimeMachine/Patches.cs:line 88
   at DMD<Il2CppAssets.Scripts.Unity.UI_New.Pause.PauseScreen::Open>(PauseScreen this, Object menuData)
   at (il2cpp -> managed) Open(IntPtr , IntPtr , Il2CppMethodInfo* )
[15:30:41.014] During invoking native->managed trampoline
[15:30:41.015] [BloonsTD6_Mod_Helper] System.MissingMethodException: Method not found: 'Il2CppAssets.Scripts.Unity.Bridge.UnityToSimulation Il2CppAssets.Scripts.Unity.UI_New.InGame.InGame.get_UnityToSimulation()'.
   at TimeMachine.TimeMachineMod.CreateTimelineUI(GameObject mainPanel, Int32 yOffset)
   at TimeMachine.PauseScreen_Open.Postfix(PauseScreen __instance) in /home/runner/work/time-machine/time-machine/TimeMachine/Patches.cs:line 88
   at DMD<Il2CppAssets.Scripts.Unity.UI_New.Pause.PauseScreen::Open>(PauseScreen this, Object menuData)
   at (il2cpp -> managed) Open(IntPtr , IntPtr , Il2CppMethodInfo* )
```

running this on windows, epic games version

**Comment by doombubbles** [comment]
Fixed with latest version https://github.com/doombubbles/time-machine/releases/tag/1.0.7
